### ISSUE TITLE
Pre Install Checker Reports Namespace Admin Permissions - Insufficient. 

### ISSUE THREAD

**Issue by lorenzk1213** [sassoftware/viya4-ark#171] opened 2022-05-24 03:02 UTC
Hi,

We have used viya4-iac to deploy the AWS environment. and used viya4-deployment DAC to deploy the baseline components,
Right now, tried to run the viy4-ark pre-install checker,
My Viya-Ark Pre-Install Checker Reports indequate permission for the Namespace Admin,
Can pls help on how to address this issue?

![Namespace Admin Insufficient Permissions](https://user-images.githubusercontent.com/104424321/169940225-920a22fe-c5da-4fcd-b6ff-c92a9ed22aa4.JPG)

Thanks,

**Comment by erharb** [comment] 2022-05-24 13:01
@lorenzk1213 these are permissions set up by whoever or whatever setup your kubernetes server. If you used IAC to create it then you may want to bring this up to them. If your kubernetes was created by someone else or your IT department then you''ll need to work with them to get your permissions corrected.

**Comment by lasiva** [comment] 2022-05-25 21:32
@lorenzk1213 
Please turn on the debug option and forward the logs to us.  I'll take a look.

**Comment by lorenzk1213** [comment] 2022-05-26 02:11
@lasiva  may I know how to turn on the debug option? if its adding -vvvv on the command, pls find attached output

[viya_pre_install_log_2022-05-23T02_02_57.log](https://github.com/sassoftware/viya4-ark/files/8775676/viya_pre_install_log_2022-05-23T02_02_57.log)

**Comment by lorenzk1213** [comment] 2022-05-26 06:57
Please find attached log with DEBUG enabled.

[viya_pre_install_log_2022-05-26T06_27_46.log](https://github.com/sassoftware/viya4-ark/files/8776950/viya_pre_install_log_2022-05-26T06_27_46.log)

*For security purposes, have deleted top portion of the log which contains AWS information

**Comment by lorenzk1213** [comment] 2022-05-26 23:47
Please find attached requested files.

**Comment by lorenzk1213** [comment] 2022-05-27 05:40
@lasiva 
I see the following 3 having Delete roles from the api-resources output. Could this be possibly a reporting tool bug?

roles                                          rbac.authorization.k8s.io/v1           true         Role                             [create delete deletecollection get list patch update watch]

rolebindings                                   rbac.authorization.k8s.io/v1           true         RoleBinding                      [create delete deletecollection get list patch update watch]

serviceaccounts                   sa           v1                                     true         ServiceAccount                   [create delete deletecollection get list patch update watch]

**Comment by lasiva** [comment] 2022-05-27 12:14
The permissions seem to be available, but I see some issues .

1. The end of the output from api-resources in your attached file shows the following:
error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request.

This results in the tool capturing the following:
Command 'kubectl -n default  api-resources -o wide' returned non-zero exit status 1,
The tool is interpreting that as insufficient Permissions. 
You might check with following command to make sure there are no issues on the cluster.  
kubectl get pods -n kube-system
Please Check if some pod are down.

2. Also the failed deletes are unable to find the resources to delete. Like following.

"/home/925408/viya4-ark-1.8.0/pre_install_report/library/utils/viya-rolebinding.yaml": rolebindings.rbac.authorization.k8s.io "viyasrolebinding" not found\n' error_out b''
The tools is interpreting Not Found as Insufficient permissions which is misleading.  

I'm not sure at this point why the tool is unable to find resources that it successfully created.  Have not hit that before.

3. Please provide the output of the "kubectl version" command also.

**Comment by lasiva** [comment] 2022-05-27 18:35
@lorenzk1213 
I'm attempting to reproduce your error.  I'll run the tool against default namespace in a clean cluster.

In the mean time we think you could go ahead and try a full deployment and not let the pre-check tool block you.

fyi... we are closed for national holiday this Monday 30th.  I may not be able to get back till late Monday or Tuesday,

Thank you

**Comment by lasiva** [comment] 2022-05-27 21:07
@lorenzk1213 
I was able to recreate your error scenario.
1. Created an AWS cluster with no Viya deployment
2. Deleted the metrics server pod
3. Issued the kubectl api-services -n kube-system command and it resulted in the same error: "error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request"
4. Finally ran the pre_install_check tool and got the same results as the one supplied by you.  The pre_install_check tool will fail some checks if the api-resources commands returns non-zero return code.  
5. Is there a metrics server installed and running?  Let us know.

![image](https://user-images.githubusercontent.com/45047672/170788070-2a55c43f-1e1b-4b28-b5fe-164d3ac2d9e4.png)
@lasiva

**Comment by lorenzk1213** [comment] 2022-05-30 23:49
Seems we do not have metric server

![image](https://user-images.githubusercontent.com/104424321/171068917-649ecf14-8569-49e6-8a0f-f16b6a30fea8.png)

**Comment by lasiva** [comment] 2022-05-31 14:25
@lorenzk1213 
The **kubectl api-services -n kube-system** command resulted in an error on you system: "error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request".  The error was in your attachment attachment per my earlier comment.
Please resolve that issue and try again.  Though the metrics server is running, the command results in non-zero return code when you run the tool.

**Comment by thpang** [comment] 2022-05-31 14:34
What helm chart is being used for the metrics servers? With k8s 1.19 and above it should be 5.11 and above : https://artifacthub.io/packages/helm/bitnami/metrics-server/5.11.0 This supports the metrics-server 0.6.0 and higher which is targeted to 1.19+

**Comment by lorenzk1213** [comment] 2022-06-01 09:51
@thpang 

We are using version 5.11.7 

![image](https://user-images.githubusercontent.com/104424321/171377602-c112d52f-8f9d-4ee7-b5dd-88abe394692b.png)

**Comment by lorenzk1213** [comment] 2022-06-01 10:10
Could this be related to the metrics-server issue in https://github.com/sassoftware/viya4-deployment/issues/230 ?

**Comment by thpang** [comment] 2022-06-01 12:01
If you code is depending on the metrics-server being installed in the cluster it would be a problem. That issue seems transient and is not related.
________________________________

**Comment by lasiva** [comment] 2022-06-01 13:07
@thpang thanks for following up.  We will look at the tool dependency on the metrics server.

**Comment by lasiva** [comment] 2022-06-02 17:19
We dont have a dependency on the metrics server but tool is looking for a clean rc from the following command:
kubectl -n default api-resources -o wide (which is failing on this issue due to metrics server).

Will investigate options further.

**Comment by erharb** [comment] 2022-06-03 13:17
If kubectl returns a non-zero code we expect it means failure. I'd recommend entering an issue against kubectl if there's not already one entered for it.

**Comment by erharb** [comment] 2022-06-06 19:57
It turns out the use of this specific kubectl command as it relates to Viya4-ark is only to determine its return code in one particular if conditional, but not actually using the data returned by the command. @lasiva has determined that this conditional is not necessary for the intended purpose of the function it is in and can be safely removed without affecting the intended behavior.

**Comment by kevinlinglesas** [comment] 2022-06-16 16:18
This issue is addressed in [Release 1.8.1](https://github.com/sassoftware/viya4-ark/releases/tag/1.8.1).

**Closed by kevinlinglesas** 2022-06-16 16:18 UTC
